force-app/main/default/objects/Formula__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>50000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Debug__c</fullName>
        <label>Debug</label>
        <length>120000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ElaborationError__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Elaboration Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <picklist>
            <picklistValues>
                <fullName>App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ExtUser</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ReturnType__c</fullName>
        <label>Return type</label>
        <picklist>
            <picklistValues>
                <fullName>BOOLEAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DATETIME</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NUMBER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>STRING</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SObjectType__c</fullName>
        <label>SObject Type</label>
        <length>45</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Scale__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Scale</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SiteSuggestions__c</fullName>
        <label>Site Suggestions</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Formula</label>
    <nameField>
        <displayFormat>F{0000000000}</displayFormat>
        <label>Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Formulas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/HierarchyCS__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>ValueNumber__c</fullName>
        <defaultValue>45.456</defaultValue>
        <label>ValueNumber (ValueNumber__c)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value (Value__c)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>HierarchyCS</label>
</CustomObject>

force-app/main/default/objects/ListCS__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>ValueNumber__c</fullName>
        <defaultValue>4.34</defaultValue>
        <label>ValueNumber (ValueNumber__c)</label>
        <precision>18</precision>
        <scale>4</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value (Value__c)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>ListCS</label>
</CustomObject>

force-app/main/default/objects/TestObject__c.object
<CustomObject>
    <label>Test Object</label>
    <nameField>
        <displayFormat>TOC{0000000000}</displayFormat>
        <label>Test Object Code (Name)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TestObject</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ApexFormulaController.cls
public without sharing class ApexFormulaController {
    public String oldFormula{get;Set;}
    public String oldComment{get;Set;}
    public String userID{get;set;}
    public String siteSuggestions{get;set;}
    public List<ListCS__c> listCustomSettings {get;set;}
    public List<HierarchyCS__c> hierarchyCustomSettings {get;set;}
    public List<TestObject__c>testObjects{get;Set;}
	public String formula{get;set;}
    //public Contact cnt{get;set;}
    public String result{get;set;}
    public String fieldsMap{get;Set;}
    public String stateV2{get;set;}
    public String outputType{get;set;}
    public String objectType{get;Set;}
    public ID loadFormulaId{get;set;}
    public List<SelectOption> formulaList{get;set;}
    public Map<String,String> limitsValues = new Map<String,String>();
    public Integer scale{get;set;}
    public ID testObjectId{get;set;}
    public List<SelectOption> sobjectsList{get;set;}
    public String limitsJSON{
        get{
            return JSON.serializePretty(this.limitsValues);
        }
    }
    public ApexFormulaController(){
        this.userID = ('ExtUser_'+Math.random()).replace('.','');
        this.formula = null;
        this.result = null; 
        this.outputType = 'BOOLEAN';
        this.formulaList = new List<SelectOption>();
        this.formulaList.add(new SelectOption('','--'));
        for(Formula__c f : [Select Id, Name__c, SObjectType__c, ReturnType__c, Scale__c 
                            From Formula__c Where Origin__c != 'ExtUser' 
                            Order By SObjectType__c, Name__c]){
            this.formulaList.add(new SelectOption(f.Id, f.Name__c+' ['+f.SObjectType__c+' - '+f.ReturnType__c+']'));
        }
		this.objectType = String.valueOf(TestObject__c.SObjectType);
        this.testObjects = [Select Id, Name, CreatedDate From TestObject__c Order By CreatedDate limit 1000];
        this.listCustomSettings=[Select Name, Value__c, ValueNumber__c From ListCS__c Order By CreatedDate];
        this.hierarchyCustomSettings = [Select Name, Value__c, ValueNumber__c From HierarchyCS__c limit 1];
        //selects the first test object
        this.testObjectId = this.testObjects[0].Id;
        //load formula from "fid" parameter
        String fid = ApexPages.currentPage().getParameters().get('fid');
        if(String.isNotBlank(fid)){
            try{
            	this.loadFormulaId = ID.valueOf(fid);
                loadFormula();
            }catcH(Exception e){
                system.debug('## EXCEPTION:'+e.getMessage());
            }
        }
	}
    
    public void selectTestObject(){}
    
    public void loadFormula(){
        if(this.loadFormulaId == null){
            return;
        }
        
        Formula__c f = [Select Id, Name__c, Body__c, ReturnType__c,Scale__c,SobjectType__c From Formula__c Where Id = :this.loadFormulaId];
        this.outputType = f.ReturnType__c;
        this.formula = f.Body__c;
        this.scale = (Integer)f.Scale__c;
        this.objectType = f.SobjectType__c;
    }
      
    public void evaluateExpression(){
        this.result = null;
        RegExps.ParserContext formulaResult = ApexExpressionParserV2.evaluate(this.formula, this.testObjectId, this.objectType, this.outputType, this.scale);
        if(formulaResult.isError != true){
        	this.result = String.valueOf(formulaResult.result);
        }else{
            this.result = null;
            ApexPages.addMessage(new ApexPages.message(ApexPages.Severity.ERROR, formulaResult.stackTrace));
        }
        
        formulaResult.formula = null;
        formulaResult.stackTrace = null;
        this.stateV2 = JSON.serializePretty(formulaResult);
        this.limitsValues = new Map<String,String>();
        this.limitsValues.put('DML Statements', Limits.getDMLStatements()+'/'+Limits.getLimitDMLStatements());
		this.limitsValues.put('DML Rows', Limits.getDMLRows()+'/'+Limits.getLimitDMLRows());
		this.limitsValues.put('Callouts', Limits.getCallouts()+'/'+Limits.getLimitCallouts());
		this.limitsValues.put('Future Calls', Limits.getFutureCalls()+'/'+Limits.getLimitFutureCalls());
		this.limitsValues.put('SOQL Queries', Limits.getQueries()+'/'+Limits.getLimitQueries());
		this.limitsValues.put('Query Rows',Limits.getQueryRows()+'/'+Limits.getLimitQueryRows());
        this.limitsValues.put('Aggregate Queries Rows',Limits.getAggregateQueries() +'/'+Limits.getLimitAggregateQueries());
        this.limitsValues.put('CPU Time',Limits.getCpuTime() +'/'+Limits.getLimitCpuTime());
        this.limitsValues.put('Heap Size',Limits.getHeapSize() +'/'+Limits.getLimitHeapSize());
        
        if(oldFormula != this.formula || this.oldComment != this.SiteSuggestions){
            Formula__c f = new Formula__c(Origin__c = 'ExtUser');
            f.ReturnType__c = this.outputType;
            f.Body__c = this.formula;
            f.Scale__c = this.scale;
            f.SobjectType__c = this.objectType;
            if(SiteSuggestions != null && SiteSuggestions.length() > 5000) SiteSuggestions = SiteSuggestions.left(5000);
            f.SiteSuggestions__c = this.SiteSuggestions;
            String debug = 'Record Id: '+this.testObjectId
                + '\n\n'
                + 'Limits: \n'+JSON.serializePretty(this.limitsValues)
                + '\n\n'
                + 'Result: '+JSON.serialize(this.result)
                + '\n\n'
                + 'Stack Trace: '+formulaResult.stackTrace
                + '\n\n'
                + 'State: \n'+ JSON.serializePretty(formulaResult);
            if(debug.length() > 100000) debug = debug.left(100000);
            f.Debug__c = debug;
            f.ElaborationError__c  =formulaResult.isError;
            if(this.userID == null) this.userID = ('ExtUser_'+Math.random()).replace('.','');
            f.Name__c = this.userID;
            insert f;
            this.oldFormula= formula;
            this.oldComment = this.SiteSuggestions;
        }
    }
}